In [1]:
import tensorflow as tf
import tensorflow_addons as tfa

In [3]:
mnist=tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test)=mnist.load_data()
x_train, x_test=x_train/255., x_test/255.

In [8]:
model=tf.keras.models.Sequential([tf.keras.layers.Reshape((28,28,1),input_shape=(28,28)),
                                 tf.keras.layers.Conv2D(10,3),
                                 tfa.layers.GroupNormalization(groups=5),
                                  tf.keras.layers.Flatten(),
                                  tf.keras.layers.Dense(128,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10, activation='softmax')
                                 ])
model.summary()
model.compile(optimizer='nadam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train, epochs=10, validation_data=(x_test,y_test))

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_3 (Reshape)          (None, 28, 28, 1)         0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 26, 26, 10)        100       
_________________________________________________________________
group_normalization_1 (Group (None, 26, 26, 10)        20        
_________________________________________________________________
flatten_1 (Flatten)          (None, 6760)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               865408    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)               

In [9]:
model=tf.keras.models.Sequential([tf.keras.layers.Reshape((28,28,1),input_shape=(28,28)),
                                 tf.keras.layers.Conv2D(10,3),
                                 tfa.layers.InstanceNormalization(),
                                  tf.keras.layers.Flatten(),
                                  tf.keras.layers.Dense(128,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10, activation='softmax')
                                 ])
model.summary()
model.compile(optimizer='nadam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train, epochs=10, validation_data=(x_test,y_test))

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_4 (Reshape)          (None, 28, 28, 1)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 26, 26, 10)        100       
_________________________________________________________________
instance_normalization (Inst (None, 26, 26, 10)        20        
_________________________________________________________________
flatten_2 (Flatten)          (None, 6760)              0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               865408    
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)               

In [1]:
import tensorflow as tf
t=[[1,2,3],[4,5,6]]
padding=[[1,1],[2,2]]
t1=tf.pad(t,padding,'CONSTANT')
t2=tf.pad(t,padding,'REFLECT')
t3=tf.pad(t,padding,'SYMMETRIC')
print(t1)
print(t2)
print(t3)

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)
